### ISSUE TITLE
The results is only about object entity prediction???

### ISSUE THREAD

**Issue by Lee-zix** [CunchaoZ/CyGNet#1]
I have checkedyour code, is your code for object entity prediction only???

**Comment by CunchaoZ** [comment]
Thank you for your question, I have modified the code.
Due to a personal oversight on my part, the previous version of the paper included only predicted object entities in the experimental results. I have corrected the experimental results in the [paper](https://arxiv.org/pdf/2012.08492.pdf).

**Comment by CunchaoZ** [comment]
Thank you for your question, I have modified the code.
The previous version of the paper included only predicted object entities in the experimental results. I have corrected the experimental results in the[ paper](https://arxiv.org/pdf/2012.08492.pdf).
