### ISSUE TITLE
time embedding

### ISSUE THREAD

**Issue by mine-sweeper** [CunchaoZ/CyGNet#2]
The timestamps in testset never appear in trainset, how do you update the embeddings of these timestamps?

**Comment by CunchaoZ** [comment]
Good question. We randomly initialize a unit step of time. A new timestamp is represented by the embedding of the last timestamp plus a time unit.

**Comment by PengpengShao** [comment]
> Good question. We randomly initialize a unit step of time. A new timestamp is represented by the embedding of the last timestamp plus a time unit.

hello, can you figure out which part of the source code represents the time update ???

**Comment by CunchaoZ** [comment]
> > Good question. We randomly initialize a unit step of time. A new timestamp is represented by the embedding of the last timestamp plus a time unit.
> 
> hello, can you figure out which part of the source code represents the time update ???

line 39-46 in link_prediction.py
