### ISSUE TITLE
I have a question on whole entity vocabulary

### ISSUE THREAD

**Issue by Ckeai** [CunchaoZ/CyGNet#7]
I found that the Figure 2 in paper shows that all entities are NBA Teams in whole entity vocabulary, but the whole entity vocabulary should consist of all entities in TKGC , not just NBA Teams. I don't know whether I understand correctly. I'd be grateful if you give me a reply!

**Comment by TCcjx** [comment]
> I found that the Figure 2 in paper shows that all entities are NBA Teams in whole entity vocabulary, but the whole entity vocabulary should consist of all entities in TKGC , not just NBA Teams. I don't know whether I understand correctly. I'd be grateful if you give me a reply!

I think you are right!
